### PR TITLE
upgrade client go version to 0.22.2 and fix int type error

### PR DESCRIPTION
**Pull request by fengshunli**

### CODE REVIEW

**Comment by ethfoo** [comment]
some golangci-lint check failed:

```
level=error msg="Running error: context loading failed: failed to load packages: failed to load with go/packages: err: exit status 1: stderr: go: inconsistent vendoring in /home/runner/work/loggie/loggie:\n\tgolang.org/x/text@v0.3.7: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgolang.org/x/time@v0.0.0-20210723032227-1f47c861a[9](https://github.com/loggie-io/loggie/runs/5549710651?check_suite_focus=true#step:4:9)ac: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgoogle.golang.org/protobuf@v1.26.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tk8s.io/api@v0.22.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tk8s.io/apimachinery@v0.22.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tk8s.io/client-go@v0.22.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tk8s.io/code-generator@v0.22.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgithub.com/xhit/go-str2duration/v2@v2.0.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod\n\tgolang.org/x/time@v0.0.0-20191024005414-555d28b269f0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod\n\tgoogle.golang.org/protobuf@v1.26.0-rc.1: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod\n\tk8s.io/api@v0.19.8: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod\n\tk8s.io/apimachinery@v0.19.8: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod\n\tk8s.io/client-go@v0.19.8: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod\n\tk8s.io/code-generator@v0.19.8: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod\n\nrun 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory\n"
```

**Comment by fengshunli** [comment]
you can delete the vendor directly and ignore it in the git file

**Comment by ethfoo** [comment]
I will create annother PR and fix this static checking

**Comment by ethfoo** [comment]
#101

**Pull request merged**
